{% set name = "pythonfmu" %}
# This needs to be updated manually => otherwise the source file won't be found
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # You need to generate the source archive with `python setup.py sdist`
  # before running this recipe
  url: ../dist/{{ name }}-{{ version }}.tar.gz
  
build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pythonfmu-builder = pythonfmu.builder:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
  run:
    - python

test:
  requires:
    - pytest
    - pyfmi
  commands:
    - pytest pythonfmu

about:
  home: https://github.com/fcollonval/PythonFMU
  summary: A lightweight framework that enables the packaging of Python3.x code as co-simulation FMUs.
  license: MIT License
  license_file: LICENSE
